---
- name: create directory for hyperbridge-relayer
  file:
    path: /home/{{ system_username }}/hyperbridge-relayer
    state: directory
    owner: "{{ system_username }}"
    group: "{{ system_username }}"

- name: copy docker compose template
  template:
    src: ./roles/hyperbridge-relayer/templates/docker-compose.yml.j2
    dest: /home/{{ system_username }}/hyperbridge-relayer/docker-compose.yml
    owner: "{{ system_username }}"
    group: "{{ system_username }}"
  register: docker

- name: copy config.toml template
  template:
    src: ./roles/hyperbridge-relayer/templates/config.toml.j2
    dest: /home/{{ system_username }}/hyperbridge-relayer/config.toml
    owner: "{{ system_username }}"
    group: "{{ system_username }}"
  register: config

- name: assure the container is (re)started
  shell: cd /home/{{ system_username }}/hyperbridge-relayer && docker compose down && docker compose up -d
  when: docker.changed or config.changed
